spring:
  sql:
    init:
      mode: always

message:
  exchange: baekma.exchange
  queue:
    delivery: delivery.queue
    hub: hub.queue
    notification: notification.queue
    company-hub-deleted: company.hub-deleted.queue
    company-order-created: company.order-created.queue
  binding-key:
    notification:
      inventory-low: hub.inventory.low
      order-created: order.created
      order-canceled: order.canceled
      order-completed: order.completed
    hub:
      route-changed: hub.route.changed
    company:
      hub-deleted: hub.deleted
      order-created: order.created

management:
  endpoints:
    web:
      exposure:
        include: health, circuitbreakers, circuitbreakerevents

  endpoint:
    health:
      show-details: always

  health:
    circuitbreakers:
      enabled: true

resilience4j:
  retry:
    instances:
      hubClient:
        max-attempts: 3
        wait-duration: 500ms
        retry-exceptions:
          - com.sparta.logistics.infrastructure.feign.exception.FeignApiException
          - feign.RetryableException
      userClient: # 추가
        max-attempts: 3
        wait-duration: 500ms
        retry-exceptions:
          - com.sparta.logistics.infrastructure.feign.exception.FeignApiException
          - feign.RetryableException
  circuitbreaker:
    instances:
      hubClient:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
      userClient:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true