spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        impl.uuid_binary_compatibility: true
  # Redis 설정, Redis 사용하지 않을 시 주석처리

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: ${OPENAI_MODEL_NAME}  # 사용할 모델
          temperature: ${OPENAI_TEMPERATURE}  # 응답의 다양성

message:
  exchange: baekma.exchange # Producer만 적용
  queue:
    notification: notification.queue
    company: company.queue
  binding-key:
    notification:
      inventory-low: hub.inventory.low
      order-created: order.created
      order-canceled: order.canceled
      order-completed: order.completed
      transmit-slack-message: notification.slack-message.transmit
    hub:
      route-changed: hub.route.changed
    company:
      hub-deleted: hub.deleted
slack:
  api:
    url: ${SLACK_API_URL:https://slack.com/api}
  bot:
    token: ${SLACK_BOT_TOKEN}
